vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        fichier_son:
            uri_prefix: '%fichier_son%'
            upload_destination: '%kernel.project_dir%/public%fichier_son%'
